name: Build and Deploy Sphinx Docs

on:
  push:
    branches:
      - master
      - previews
  workflow_dispatch:  # allow manual trigger

permissions:
  contents: write 

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sphinx sphinx-autobuild sphinx-rtd-theme sphinx-apidoc
      
      - name: Generate API docs
        run: |
          python -m sphinx.ext.apidoc -o source/interface interface
          python -m sphinx.ext.apidoc -o source/system system

      - name: Build documentation
        run: |
          sphinx-build -b html source build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build
